### PR TITLE
Update to work with the Datastax ruby-driver gem

### PR DESCRIPTION
**Pull request by mdimas**
@vijaykramesh @davidmarotto

### CODE REVIEW

**Comment by vijaykramesh** [comment]
we'll want to pin the version in the monorail to the old version of this (currently unpinned) - until we update the monorail to use the datastax driver.

**Comment by mdimas** [comment]
OK, I'll update it to use the "0.1.0" tag

**Comment by mdimas** [comment]
@vijaykramesh see https://github.com/change/change_production/pull/3572

**Comment by vijaykramesh** [comment]
awesome LGTM!

**Pull request merged**
